import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Eretz Realty Admin System Documentation Structure
 *
 * This sidebar configuration organizes the documentation into two main sections:
 * 1. User Documentation - For end users and administrators
 * 2. Technical Documentation - For developers and system architects
 */
const sidebars: SidebarsConfig = {
  // User Documentation Sidebar
  userDocsSidebar: [
    {
      type: 'doc',
      id: 'user-documentation/index',
      label: '📖 Introduction',
    },
    {
      type: 'doc',
      id: 'user-documentation/getting-started',
      label: '🚀 Getting Started',
    },
    {
      type: 'category',
      label: '📊 Core Features',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'user-documentation/dashboard-cycle-manager',
          label: 'Dashboard & Cycle Manager',
        },
        {
          type: 'doc',
          id: 'user-documentation/managing-listings',
          label: 'Managing Listings',
        },
        {
          type: 'doc',
          id: 'user-documentation/email-campaigns',
          label: 'Email Campaign Management',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Configuration',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'user-documentation/schedule-configuration',
          label: 'Schedule Configuration',
        },
        {
          type: 'doc',
          id: 'user-documentation/email-recipients',
          label: 'Email Recipients Management',
        },
        {
          type: 'doc',
          id: 'user-documentation/lookup-tables',
          label: 'Lookup Tables Management',
        },
      ],
    },
    {
      type: 'category',
      label: '👥 Administration',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'user-documentation/user-management',
          label: 'User Management (Admin Only)',
        },
      ],
    },
  ],

  // Technical Documentation Sidebar (placeholder for future content)
  technicalDocsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'technical-documentation',
    },
  ],
};

export default sidebars;
